name: Karate CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java 17 (necesario para Karate)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Ejecutar los tests con Maven
      - name: Run Karate tests
        run: mvn clean test

      # 4️⃣ Guardar el reporte HTML generado
      - name: Upload Karate HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: karate-html-report
          path: target/karate-reports
